### ISSUE TITLE
Figures 10.1 and 11.7 are not displayed

### ISSUE THREAD

**Issue by brunogirin** [volaya/gis-book#9]
Figure 10.1 in the **Analysis** chapter and figure 11.7 in the **Visualization of geographical data** chapter fail to display, see below:

## Figure 10.1

![selection_324](https://user-images.githubusercontent.com/216028/41441204-8f2653aa-7029-11e8-8ca8-5bedf7fcd7dc.png)

## Figure 11.7

![selection_325](https://user-images.githubusercontent.com/216028/41441387-4e7a0b34-702a-11e8-8103-17e2427eb6cc.png)

**Comment by volaya** [comment]
fixes
